language: rust
sudo: true
cache: cargo
os:
  - linux

matrix:
  fast_finish: false
  include:
  - rust: stable
    script:
      # Run tests/builds
      - cargo check
      - cargo build --release --verbose --all
      - cargo test --release --verbose --all
      
  
  - rust: nightly
    script:
      # Run tests/builds
      - cargo check
      - cargo build --release --verbose --all
      - cargo test --release --verbose --all


# Send a notification to the Dusk build Status Telegram channel once the CI build completes
after_script:
  - bash <(curl -s https://raw.githubusercontent.com/dusk-network/tools/master/bash/telegram_ci_notifications.sh)

after_success:
# Upload docs
- |
    if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "nightly" && "$TRAVIS_PULL_REQUEST" = "false" && "$TRAVIS_BRANCH" == "master" ]]; then
      cargo doc --no-deps &&
      echo "<meta http-equiv=refresh content=0;url=poseidon252/index.html>" > target/doc/index.html &&
      git clone https://github.com/davisp/ghp-import.git &&
      ./ghp-import/ghp_import.py -n -p -f -m "Documentation upload" -r https://"$GH_TOKEN"@github.com/"$TRAVIS_REPO_SLUG.git" target/doc &&
      echo "Uploaded documentation"
    fi


