on:
  pull_request:
  push:
    branches:
      - master

name: Continuous integration

jobs:
  code-quality:
    name: Code quality
    uses: dusk-network/.github/.github/workflows/run-make.yml@main
    with:
      make_target: cq

  test:
    name: Run tests
    uses: dusk-network/.github/.github/workflows/run-make.yml@main
    with:
      make_target: test

  no-std:
    name: Run no-std checks
    uses: dusk-network/.github/.github/workflows/run-make.yml@main
    with:
      make_target: no-std

  build_benches:
    name: Build Benchmarks
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - uses: Swatinem/rust-cache@v2
      - run: cargo bench --all-features --no-run
